import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Terms of Service - InterviewPreview",
  description:
    "Terms of service for InterviewPreview. Read the terms governing your use of our platform.",
};

export default function TermsPage() {
  return (
    <>
      <Header />

      <div className="section-container py-24">
        <div className="max-w-3xl mx-auto animate-fade-in">
          <p className="label-tag mb-4">Legal</p>
          <h1 className="font-display text-4xl md:text-5xl font-semibold text-ink mb-4">
            Terms of Service
          </h1>
          <p className="text-sm text-ink-secondary mb-12">
            Last updated: February 25, 2026
          </p>

          <div className="prose-custom space-y-8">
            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                1. Acceptance of Terms
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                By accessing or using InterviewPreview
                (&quot;interviewpreview.com&quot;, &quot;we&quot;,
                &quot;us&quot;, or &quot;our&quot;), you agree to be bound by
                these Terms of Service. If you do not agree to these terms,
                please do not use our service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                2. Description of Service
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                InterviewPreview is an AI-powered mock interview platform that
                generates interview questions, evaluates your answers, and
                provides feedback. The service is intended for personal
                interview preparation and educational purposes.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                3. User Accounts
              </h2>
              <ul className="list-disc pl-6 space-y-2 text-sm text-ink-secondary leading-relaxed">
                <li>
                  You are responsible for maintaining the confidentiality of your
                  account credentials.
                </li>
                <li>
                  You are responsible for all activity that occurs under your
                  account.
                </li>
                <li>
                  You must provide accurate and complete information when
                  creating an account.
                </li>
                <li>
                  You must notify us immediately of any unauthorised use of your
                  account.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                4. Acceptable Use
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed mb-3">
                You agree not to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-sm text-ink-secondary leading-relaxed">
                <li>
                  Use the service for any unlawful purpose or in violation of
                  any applicable laws.
                </li>
                <li>
                  Attempt to gain unauthorised access to any part of the service
                  or its systems.
                </li>
                <li>
                  Interfere with or disrupt the service or servers connected to
                  the service.
                </li>
                <li>
                  Use automated tools to scrape, crawl, or extract data from the
                  service.
                </li>
                <li>
                  Share, resell, or redistribute your account access or content
                  generated by the service.
                </li>
                <li>
                  Upload malicious content, spam, or content that infringes on
                  the rights of others.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                5. Subscriptions and Payments
              </h2>
              <ul className="list-disc pl-6 space-y-2 text-sm text-ink-secondary leading-relaxed">
                <li>
                  Free accounts are subject to usage limits as described on our
                  pricing page.
                </li>
                <li>
                  Pro subscriptions are billed monthly and renew automatically
                  unless cancelled.
                </li>
                <li>
                  You may cancel your subscription at any time. Access continues
                  until the end of your current billing period.
                </li>
                <li>
                  We reserve the right to change pricing with reasonable notice.
                  Existing subscribers will be notified before any price changes
                  take effect.
                </li>
                <li>
                  All payments are processed securely through Stripe. We do not
                  store your payment card details.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                6. Refund Policy
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                If you are unsatisfied with your Pro subscription, you may
                request a refund within 7 days of your initial purchase by
                contacting us at{" "}
                <a
                  href="mailto:isaac@betternetworks.com.au"
                  className="text-accent hover:text-accent/80 transition-colors"
                >
                  isaac@betternetworks.com.au
                </a>
                . Refunds are not available for subsequent billing cycles after
                the initial 7-day period.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                7. Intellectual Property
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                All content, features, and functionality of the service
                (including but not limited to text, graphics, logos, and
                software) are the property of InterviewPreview and are protected
                by intellectual property laws. You retain ownership of the
                content you submit (e.g., CV summaries, interview answers), but
                grant us a licence to use it for the purpose of providing the
                service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                8. AI-Generated Content
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                Interview questions, evaluations, and feedback are generated by
                artificial intelligence. While we strive for accuracy and
                helpfulness, AI-generated content should not be considered
                professional career advice. Scores and feedback are for
                preparation purposes only and do not guarantee interview
                outcomes.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                9. Limitation of Liability
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                To the maximum extent permitted by law, InterviewPreview shall
                not be liable for any indirect, incidental, special,
                consequential, or punitive damages, or any loss of profits or
                revenues, whether incurred directly or indirectly, or any loss
                of data, use, or goodwill arising out of your use of the
                service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                10. Disclaimer of Warranties
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                The service is provided &quot;as is&quot; and &quot;as
                available&quot; without warranties of any kind, either express or
                implied, including but not limited to implied warranties of
                merchantability, fitness for a particular purpose, and
                non-infringement.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                11. Termination
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                We reserve the right to suspend or terminate your account at our
                discretion, without notice, if you violate these Terms of
                Service or engage in conduct that we determine to be harmful to
                the service or other users. Upon termination, your right to
                access the service will immediately cease.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                12. Changes to These Terms
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                We may update these Terms of Service from time to time. We will
                notify you of significant changes by posting the updated terms on
                this page. Your continued use of the service after changes are
                posted constitutes your acceptance of the revised terms.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                13. Governing Law
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                These Terms of Service shall be governed by and construed in
                accordance with the laws of Australia, without regard to its
                conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-semibold text-ink mb-3">
                14. Contact Us
              </h2>
              <p className="text-sm text-ink-secondary leading-relaxed">
                If you have any questions about these Terms of Service, please
                contact us at{" "}
                <a
                  href="mailto:isaac@betternetworks.com.au"
                  className="text-accent hover:text-accent/80 transition-colors"
                >
                  isaac@betternetworks.com.au
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
